import { comments } from "./comentsData";

export const postArray = [
  {
    id: "1",
    photo: "https://i.pravatar.cc/1000?img=11",
    name: "Gabriel Cooper",
    description: "Dev Front-End",
    timing: "2",
    apresentation: "Fala galeraa 👋",
    text: "Acabei de subir mais um projeto no meu portifa. É um projeto que fiz para meu desenvolvimento na LM Tech. O nome do projeto é Ignite Feed Project 🚀",
    link: "👉 ",
    linkSpan: "jane.design/doctorcare",
    hashtags: "#novoprojeto #nlw #rocketseat",
    comments: [],
  },
  {
    id: "2",
    photo: "https://i.pravatar.cc/1000?img=10",
    name: "Vitor Lane",
    description: "Dev Back-End",
    timing: "1",
    apresentation: "Fala pessoal 👋",
    text: "Finalmente finalizei meu novo site/portfólio. Foi um baita desafio criar todo o design e codar na unha, mas consegui 💪🏻 ",
    link: "Acesse e deixe seu feedback 👉 ",
    linkSpan: "devonlane.design",
    hashtags: "#uiux #userexperience",
    comments: [comments[1], comments[2], comments[3]],
  },
  {
    id: "3",
    photo: "https://i.pravatar.cc/1000?img=12",
    name: "Kaique Bruneto",
    description: "Dev Fullstack",
    timing: "4",
    apresentation: "Opa, e aí pessoal. Tudo bem? 👋",
    text: "Fiz esse projeto para aprimorar meus conhecimentos e aumentar meu portfólio. Foi enriquecedor em conhecimentos, show! 🚀",
    link: "Pode dar uma olhadinha? 👉 ",
    linkSpan: "github.com/confia/que-vai",
    hashtags: "#dev #devfullstack",
    comments: [comments[4], comments[5]],
  },
];
